#!/bin/bash

date
echo GITHUB_ACTOR=$GITHUB_ACTOR
echo GITHUB_REF_NAME=$GITHUB_REF_NAME
echo GITHUB_SHA=$GITHUB_SHA
echo CUSTOM_VAR1=$CUSTOM_VAR1
echo CUSTOM_VAR2=$CUSTOM_VAR2
echo CUSTOM_VARx=$CUSTOM_VARx
echo REPO_VAR=$REPO_VAR

