  name: check docker image exists
  on:
    push:
  jobs:
    context:
      runs-on: ubuntu-latest
      continue-on-error: true  
      steps:  
        - name: Check image
          id: image_exists
          uses: cloudposse/github-action-docker-image-exists@main
          with:
            registry: registry.hub.docker.com
            organization: ocfork
            repository: secretsmanagement-operator
            #login: "${{ secrets.DOCKERHUB_USERNAME }}"
            #password: "${{ secrets.DOCKERHUB_PASSWORD }}"
            tag: "0.1.0-x"
        - name: show results
          run: |
            echo conclusion=${{ steps.image_exists.conclusion }}
            # conclusion=success
            echo image=${{ steps.image_exists.outputs.image }}
            # image=registry.hub.docker.com/ocfork/secretsmanagement-operator
            echo tag=${{ steps.image_exists.outputs.tag }}          
            #tag=0.1.0 

