  name: check docker image exists
  on:
    push:
  jobs:
    context:
      runs-on: ubuntu-latest
      steps:  
        - name: Check if image exist
          # https://github.com/marketplace/actions/docker-exist-action
          id: is_image_exist
          uses: KerberosMorphy/docker-exist-action@v1.1.1
          with:
            registry: docker.io
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
            image: ocfork/secretsmanagement-operator>0.1.0-x
        - name: Publish Image if not exist
          if: ((!steps.is_image_exist.outputs.image_exist))
          run: echo "image does not exist"
        - name: Show error if image already exists
          if: ((steps.is_image_exist.outputs.image_exist))
          run: echo "image already exist"
