name: Build Alpine-Helm Dockerimage
run-name: Build Alpine-Helm Dockerimage
on: 
  push:
    # see https://www.techielass.com/trigger-a-github-action-workflow-when-a-folder-changes/
    #paths:
    #- alpine-helm/**/*
jobs:
  # see https://docs.docker.com/build/ci/github-actions/reproducible-builds/
  #     https://docs.docker.com/build/ci/github-actions/push-multi-registries/
  build-alpine-helm-dockerfile-job:
    runs-on: ubuntu-latest
    steps:
    
      - name: read versionnumber of secretsmanagement-operator from values.yaml
        id: get_smanop_version
        uses: mikefarah/yq@master
        with:
          cmd: yq '.secretsmanagement-operator.version' charts/canvas-oda/values.yaml
          
      - name: Reuse a variable obtained in another step
        run: echo ${{ steps.get_smanop_version.outputs.result }}
        
#      - name: Checkout
#        uses: actions/checkout@v4
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#      
#      - name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#                
#      - name: Get Git commit timestamps
#        run: echo "TIMESTAMP=$(git log -1 --pretty=%ct)" >> $GITHUB_ENV
#      
#      - name: Build and push
#        uses: docker/build-push-action@v5
#        with:
#          context: alpine-helm
#          platforms: linux/amd64,linux/arm64
#          push: true
#          tags: |
#            feridock/alpine-helm:latest
#            feridock/alpine-helm:1.0.0
#        env:
#          SOURCE_DATE_EPOCH: ${{ env.TIMESTAMP }}
