name: Build Alpine-Helm Dockerimage
run-name: Build Alpine-Helm Dockerimage
on: 
  push:
jobs:
  modify_job:
    runs-on: ubuntu-latest
    steps:
      # We'll need to check out the repository so that we can edit the README.
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Let's get all the branches.

      - name: show files recursive
        run: |
          find .
          git status
      
      - name: check file exists
        id: fileexists
        shell: bash
        run: |
          if [ -f testfile.txt ]
          then
            echo "testfile.txt exists"
            echo "test=true" >> "$GITHUB_OUTPUT"
          else            
            echo "test=false" >> "$GITHUB_OUTPUT"
          fi
          echo "$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT"

      - name: ifexists
        if: steps.fileexists.outputs.test == "true"
        run: |
          echo "IFEXISTS"
          echo "${{ steps.fileexists.outputs.test }}"    
          rm testfile.txt
          git config --global github-action-bot 'GitHub Action Bot'
          git config --global user.email 'github-action-bot@invalid.ignore'
          git commit -am "removed testfile.txt"
          git push
        
      
      - name: ifnotexists
        if: steps.fileexists.outputs.test != "true"
        run: |
            echo "IFNOTEXISTS"
            echo "${{ steps.fileexists.outputs.test }}"    
      
      - name: show files
        run: ls -la    
