name: Remove Prerelease Suffix on main branch
run-name: Remove Prerelease Suffix on main branch
on: 
  pull_request_target:
    types:
      - closed
    branches:
      - 'main'
jobs:
  remove_prerelease_suffices:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Let's get all the branches.
      - uses: chrisdickinson/setup-yq@latest
        with:
          yq-version: 'v4.44.1'
          #yq-url: 'https://github.com/mikefarah/yq/releases/download/v4.44.1/yq_linux_amd64'
      - shell: bash
        run: |
          PRERELEASE=$(yq '.secretsmanagement-operator.prereleaseSuffix' charts/canvas-oda/values.yaml)
          echo "PRERELEASE=$PRERELEASE"
          if [ -n "$PRERELEASE" ]
          then
              yq -i '.secretsmanagement-operator.prereleaseSuffix=""' charts/canvas-oda/values.yaml
              git config --global user.name 'GitHub Action Bot'
              git config --global user.email 'github-action-bot@invalid.ignore'
              git commit -am "removed secretsmanagement-operator.prereleaseSuffix $PRERELEASE"
              git push
          fi          
